version: '3'

services:
    db:
      build:
        context: .
        dockerfile: 'Dockerfile'
      ports:
        - 5434:5432
      environment:
        - POSTGRES_DB=docker_showcase
        - POSTGRES_USER=docker_user
      container_name: backup_postgres